config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'

  root 'homes#index'

  resources :teams, only: [:index, :show, :edit, :update]
  resources :players

  resources :sites, only: [:index, :show]  do
    get '/games/:year/:month/:day' => 'games#date', as: :games_date, constraints: {
      year:       /\d{4}/,
      month:      /\d{1,2}/,
      day:        /\d{1,2}/
    }

    post '/games/:year/:month/:day/player_costs_uploads' => 'player_costs_uploads#create', as: :player_costs_uploads, constraints: {
      year:       /\d{4}/,
      month:      /\d{1,2}/,
      day:        /\d{1,2}/
    }

    resources :player_costs, only: [:update, :index]

    resources :lineups, only: [:index]

  end

  resources :games, only: [:index, :show]

  resources :stats, only: [:index]

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id           :integer          not null, primary key
#  nba_id       :string(255)
#  date         :datetime
#  home_team_id :integer
#  away_team_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Game < ActiveRecord::Base

  default_scope { order('date DESC') }

  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"

  has_many :player_costs
  has_many :stat_lines

  scope :today, -> {where(date: Date.today.strftime('%F'))}
  scope :on_date, lambda{ |date| where("date = ?", date) }
  scope :this_season, -> { where('date > ?', Date.new(2014, 10, 27)) }

  def home_team_against_position
    stats = {}
    stats["PG"] = 0
    stats["SG"] = 0
    stats["SF"] = 0
    stats["PF"] = 0
    stats["C"] = 0
    self.stat_lines.where(team_id: home_team_id).each do |sl|
      pc = self.player_costs.primary.find_by_player_id(sl.player_id)
      if !pc.nil?
        stats[pc.position] += sl.score_draft_kings
      end
    end
    return stats
  end

  def away_team_against_position
    stats = {}
    stats["PG"] = 0
    stats["SG"] = 0
    stats["SF"] = 0
    stats["PF"] = 0
    stats["C"] = 0
    self.stat_lines.where(team_id: away_team_id).each do |sl|
      pc = self.player_costs.primary.find_by_player_id(sl.player_id)
      if !pc.nil?
        stats[pc.position] += sl.score_draft_kings
      end
    end
    return stats
  end

  def display_title
    "#{away_team.full_name} at #{home_team.full_name}"
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_site, only: [:date]
  before_action :set_game, only: [:show]

  def index
    @games = Game.all
  end

  def date
    @date = Date.new(params[:year].to_i,params[:month].to_i,params[:day].to_i)
    @games = Game.on_date(@date)#Game.where(date: @date..@date+1.day-1.hour)
  end

  def show
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def set_site
    @site = Site.find(params[:site_id])
  end

end

app/views/games/date.html.erb
<h1><%= link_to @site.name, site_path(@site) %></h1>

<div ng-controller="GameDayCtrl">
  <div id="date-info" data-year="<%= @date.year %>" data-month="<%= @date.month %>" data-day="<%= @date.day %>"></div>
  <div id="site-info" data-site-id="<%= @site.id %>"></div>

  <div class="row">
    <div class="col-md-6">
      <h1><%= @date %></h1>
    </div>
    <% if current_user %>
      <div class="col-md-6">
        <h2>Upload Your Own Projections</h2>
        <%= form_tag({controller: :player_costs_uploads, action: :create}, multipart: true) do %>
          <%= file_field_tag 'projections' %>
          <%= submit_tag 'Upload', :class => "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <% @games.each do |game| %>
        <div class="row">
          <div class="col-md-12">
            <label><input type="checkbox" checked class="ginfo" data-gid="<%= game.id %>"></input><%="#{game.away_team.full_name} at #{game.home_team.full_name}"%><%= link_to "(link)", game %></label>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <h4>Locked</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Pos</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Expected Points</th>
            <th>Locked?</th>
            <th>Out</th>
          </tr>
        </thead>
        <tbody class="pcs-healthy">
            <tr ng-repeat="player in players | filter:{locked:'true'} | orderBy:'-expected_points'">
              <td>{{player.position}}</td>
              <td><a href="/players/{{player.player.id}}">{{player.player.first_name}} {{player.player.last_name}}</a></td>
              <td>{{player.salary}}</td>
              <td>{{player.expected_points | number:2}}</td>
              <td ng-show="player.locked"><button ng-click="playerUnlock(player)" class="btn btn-success pc-unlock">Unlock</button></td>
              <td ng-hide="player.locked"><button ng-click="playerLock(player)" class="btn btn-error pc-lock">Lock</button></td>
              <td><button ng-click="playerOut(player)" class="btn btn-warning pc-out">Out</button></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <button class="btn btn-success" ng-click="generateLineups()" id="generate-lineup">Generate Lineup</button>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Pos</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Expected Points</th>
            <th>Actual Points</th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat="player in lineup1.players">
            <td class="position">{{player.position}}</td>
            <td class="name"><a href="/players/{{player.player.id}}">{{player.player.full_name}}</a></td>
            <td class="salary">{{player.salary}}</td>
            <td class="expected-points">{{player.expected_points | number:2}}</td>
            <td class="actual-points-dk">{{player.actual_points | number:2}}</td>
          </tr>
        </tbody>
      </table>
      <div>
        Total Salary: <span id="lineup-salary">{{lineup1.salary | number:2}}</span>
      </div>
      <div>
        Expected Points: <span id="lineup-expected-points">{{lineup1.expected_points | number:2}}</span>
      </div>
      <div>
        Actual Points: <span id="lineup-actual-points-dk">{{lineup1.actual_points_dk | number:2}}</span>
      </div>
    </div>

    <div class="col-md-6">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Pos</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Expected Points</th>
            <th>Actual Points</th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat="player in lineup2.players">
            <td class="position">{{player.position}}</td>
            <td class="name"><a href="/players/{{player.player.id}}">{{player.player.full_name}}</a></td>
            <td class="salary">{{player.salary}}</td>
            <td class="expected-points">{{player.expected_points | number:2}}</td>
            <td class="actual-points-dk">{{player.actual_points | number:2}}</td>
          </tr>
        </tbody>
      </table>
      <div>
        Total Salary: <span id="lineup-salary">{{lineup2.salary}}</span>
      </div>
      <div>
        Expected Points: <span id="lineup-expected-points">{{lineup2.expected_points | number:2}}</span>
      </div>
      <div>
        Actual Points: <span id="lineup-actual-points-dk">{{lineup2.actual_points_dk | number:2}}</span>
      </div>
    </div>

  </div>


  <div class="row">
    <div class="col-md-6">
      <h4>In</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Pos</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Expected Points</th>
            <th>Locked?</th>
            <th>Out</th>
          </tr>
        </thead>
        <tbody class="pcs-healthy">
            <tr ng-repeat="player in players | filter:{healthy:'true'} | orderBy:'-expected_points'">
              <td>{{player.position}}</td>
              <td><a href="/players/{{player.player.id}}">{{player.player.first_name}} {{player.player.last_name}}</a></td>
              <td>{{player.salary}}</td>
              <td>{{player.expected_points | number:2}}</td>
              <td ng-show="player.locked"><button ng-click="playerUnlock(player)" class="btn btn-success pc-unlock">Unlock</button></td>
              <td ng-hide="player.locked"><button ng-click="playerLock(player)" class="btn btn-error pc-lock">Lock</button></td>
              <td><button ng-click="playerOut(player)" class="btn btn-warning pc-out">Out</button></td>
            </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <h4>Out</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Pos</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Expected Points</th>
            <th>Out</th>
          </tr>
        </thead>
        <tbody class="pcs-healthy">
            <tr ng-repeat="player in players | filter:{healthy:'false'} | orderBy:'-expected_points'">
              <td>{{player.position}}</td>
              <td><a href="/players/{{player.player.id}}">{{player.player.first_name}} {{player.player.last_name}}</a></td>
              <td>{{player.salary}}</td>
              <td>{{player.expected_points | number:2}}</td>
              <td><button ng-click="playerIn(player)" class="btn btn-warning pc-out">In</button></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="row">
  <div class="col-md-6">
  </div>
</div>
<div class="row">
  <div class="col-md-6">
  </div>
</div>

app/views/games/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h3><%= link_to @game.away_team.full_name, @game.away_team %> at <%= link_to @game.home_team.full_name, @game.home_team %></h3>
    <h4><%= link_to @game.date, games_date_path(year: @game.date.year, month: @game.date.month, day: @game.date.day) %></h4>
  </div>
</div>

<div class="row">
  <h2><%= link_to @game.home_team.full_name, @game.home_team %></h2>
  <%= render partial: "stat_lines/table", locals: {stat_lines: @game.stat_lines.where(team_id: @game.home_team_id)} %>
</div>

<div class="row">
  <h2><%= link_to @game.away_team.full_name, @game.away_team %></h2>
  <%= render partial: "stat_lines/table", locals: {stat_lines: @game.stat_lines.where(team_id: @game.away_team_id)} %>
</div>