config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'

  root 'homes#index'

  resources :teams, only: [:index, :show, :edit, :update]
  resources :players

  resources :sites, only: [:index, :show]  do
    get '/games/:year/:month/:day' => 'games#date', as: :games_date, constraints: {
      year:       /\d{4}/,
      month:      /\d{1,2}/,
      day:        /\d{1,2}/
    }

    post '/games/:year/:month/:day/player_costs_uploads' => 'player_costs_uploads#create', as: :player_costs_uploads, constraints: {
      year:       /\d{4}/,
      month:      /\d{1,2}/,
      day:        /\d{1,2}/
    }

    resources :player_costs, only: [:update, :index]

    resources :lineups, only: [:index]

  end

  resources :games, only: [:index, :show]

  resources :stats, only: [:index]

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id               :integer          not null, primary key
#  team_id          :integer
#  first_name       :string(255)
#  last_name        :string(255)
#  underscored_name :string(255)
#  nba_id           :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Player < ActiveRecord::Base

  belongs_to :team

  has_many :player_costs
  has_many :stat_lines

  def prev_stat_lines(date = Date.today, lookback = nil)
    lookback ||= self.stat_lines.count
    self.stat_lines.before_date(date).take(lookback)
  end

  def median_points(date, lookback)
    stat_lines = self.prev_stat_lines(date, lookback)
    len = stat_lines.length
    if stat_lines.length == 0
      return 0
    elsif stat_lines.length == 1
      return stat_lines.first.score_draft_kings
    elsif stat_lines.length == 2
      return (stat_lines.first.score_draft_kings + stat_lines.first.score_draft_kings)/2.0
    else
      stat_lines[(len-1) / 2].score_draft_kings + stat_lines[len/2].score_draft_kings / 2.0
    end
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def on_team?(team)
    self.team.id == team.id
  end

  def fan_duel_std_dev
    scores = self.stat_lines.played.map(&:score_fan_duel)
    DfsStats::Basic.standard_deviation(scores)
  end

  def avg_draft_kings
    scores = self.stat_lines.played.map(&:score_draft_kings)
    scores.sum.to_f / scores.length
  end

  def avg_minutes
    minutes = self.stat_line.map(&:minutes)
    minutes.inject(:+).to_f / minutes.length
  end

  def avg_fan_duel_points
    self.stat_lines.played
  end

  def fan_duel_points_per_minute
    self.avg_fan_duel_points / self.avg_minutes
  end

  def minutes
    data = Hash.new(0)
    #default hash?
    (0..40).each do |num|
      data[num] = []
    end
    StatLine.played.each do |stat|
      data[stat.minutes] << stat.score_fan_duel
    end
    ret = []
    (0..40).each do |num|
      if data[num].length == 0
        ret << 0
      else
        ret << data[num].inject{ |sum, el| sum + el }.to_f / data[num].length
      end
    end
    ret
  end

  def to_json
    data = {}
    data[:full_name] = self.full_name
    data[:id] = self.id
    data
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
  end

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  private

    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def player_params
      params[:player].permit(:city, :mascot, :abbreviation, :nba_id, :division_id, :alternate_name)
    end
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="">First Name</label>
    <%= f.text_field :first_name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Last Name</label>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="row">
  <div class="col-md-6">

    <h1>Editing player</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @player%> |
    <%= link_to 'Back', players_path %>
  </div>
</div>

app/views/players/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Listing Players</h1>
  </div>
</div>
<% @players.each do |player|%>
  <div class="row">
    <div class="col-md-6">
      <%= link_to player.full_name, player_path(player) %>
    </div>
  </div>
<% end %>

app/views/players/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>New player</h1>

    <%= render 'form' %>

    <%= link_to 'Back', players_path %>
  </div>
</div>

app/views/players/show.html.erb
<h1><%= @player.full_name %></h1>

<%= render partial: "stat_lines/player_table", locals: {stat_lines: @player.stat_lines.played} %>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>