config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'

  root 'homes#index'

  resources :teams, only: [:index, :show, :edit, :update]
  resources :players

  resources :sites, only: [:index, :show]  do
    get '/games/:year/:month/:day' => 'games#date', as: :games_date, constraints: {
      year:       /\d{4}/,
      month:      /\d{1,2}/,
      day:        /\d{1,2}/
    }

    post '/games/:year/:month/:day/player_costs_uploads' => 'player_costs_uploads#create', as: :player_costs_uploads, constraints: {
      year:       /\d{4}/,
      month:      /\d{1,2}/,
      day:        /\d{1,2}/
    }

    resources :player_costs, only: [:update, :index]

    resources :lineups, only: [:index]

  end

  resources :games, only: [:index, :show]

  resources :stats, only: [:index]

end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Site < ActiveRecord::Base

  has_many :player_costs

  def fan_duel?
    self.name == "Fan Duel"
  end

  def draft_kings?
    self.name == "Draft Kings"
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
    beginning_of_season = Date.new(2014, 10, 27)
    @dates = Date.today.downto(beginning_of_season)
  end

  private

end

app/views/sites/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Listing Sites</h1>
  </div>
</div>
<% @sites.each do |site|%>
  <div class="row">
    <div class="col-md-6">
      <%= link_to site.name, site_path(site) %>
    </div>
  </div>
<% end %>

app/views/sites/show.html.erb
<h1><%= @site.name %></h1>

<div class="row">
  <div class="col-md-6">
    <%= link_to "Today", site_games_date_path(site_id: @site.id, day: Date.today.day, month: Date.today.month, year: Date.today.year) %>
  </div>
</div>

<% @dates.each do |date| %>
  <div class="row">
    <div class="col-md-6">
      <%= link_to date, site_games_date_path(site_id: @site.id, day: date.day, month: date.month, year: date.year) %>
    </div>
  </div>
<% end %>